version: 2.1

commands:
  set_package_version:
    description: Set version statically
    steps:
      - run:
          name: Set version statically
          command: |
            VERSION=$(python3 setup.py --version)
            sed -i "s/setup_requires=.*/version='$VERSION',/; s/use_scm_version=.*//" setup.py

jobs:

  test_python26:
    docker:
      - image: danielflook/python-minifier-build:fedora30-2020-05-03
    steps:
      - checkout
      - set_package_version

      - run:
          name: tox
          command: |
            pip3 install 'tox<3' 'virtualenv<16'
            tox -r -e python26

  test_python33:
    docker:
      - image: danielflook/python-minifier-build:fedora28-2020-05-03
    steps:
      - checkout
      - set_package_version

      - run:
          name: tox
          command: |
            pip3 install 'tox<3' 'virtualenv<16'
            tox -r -e python33

  test_python39:
    docker:
      - image: danielflook/python-minifier-build:fedora32-2020-10-11
    steps:
      - checkout
      - set_package_version

      - run:
          name: tox
          command: |
            pip3 install tox==3.20
            tox -r -e python39

  test:
    docker:
      - image: danielflook/python-minifier-build:fedora30-2020-05-03
    steps:
      - checkout
      - set_package_version

      - run:
          name: tox
          command: |
            pip3 install tox==3.11.1 virtualenv==16.6.0
            tox -r -e python27,python34,python35,python36,python37,python38,pypy,pypy3

  xtest:
    docker:
      - image: danielflook/python-minifier-build:<< parameters.image >>
    steps:
      - checkout
      - set_package_version

      - run:
          name: tox
          command: |

            if [[ "<< parameters.interpreter >>" == "python26" ]]; then
              pip3 install 'tox<3' 'virtualenv<16'
            elif [[ "<< parameters.interpreter >>" == "python33" ]]; then
              pip3 install 'tox<3' 'virtualenv<16'
            elif [[ "<< parameters.interpreter >>" == "python39" ]]; then
              pip3 install tox==3.20
            else
              pip3 install tox==3.11.1 virtualenv==16.6.0
            fi

            tox -r -e << parameters.interpreter >> xtest

    parameters:
      interpreter:
        type: string
      image:
        type: string
        default: fedora30-2020-05-03

workflows:
  version: 2
  build:
    jobs:
      - test_python26
      - test_python33
      - test_python39
      - test

#      - xtest:
#          name: xtest_python26
#          interpreter: python26
#          requires:
#            - test_python26
#      - xtest:
#          name: xtest_python27
#          interpreter: python27
#          requires:
#            - test
#      - xtest:
#          name: xtest_python33
#          interpreter: python33
#          image: fedora28-2020-05-03
#          requires:
#            - test_python33
#      - xtest:
#          name: xtest_python34
#          interpreter: python34
#          requires:
#            - test
#      - xtest:
#          name: xtest_python35
#          interpreter: python35
#          requires:
#            - test
#      - xtest:
#          name: xtest_python36
#          interpreter: python36
#          requires:
#            - test
#      - xtest:
#          name: xtest_python37
#          interpreter: python37
#          requires:
#            - test
#      - xtest:
#          name: xtest_python38
#          interpreter: python38
#          image: fedora30-2019-10-20
#          requires:
#            - test
#      - xtest:
#          name: xtest_python39
#          interpreter: python39
#          image: fedora32-2020-10-11
#          requires:
#            - test_python39
#      - xtest:
#          name: xtest_pypy3
#          interpreter: pypy3
#          image: fedora30-2019-10-20
#          requires:
#            - test
